%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Serkan\git\cmpe362hw3\exampleSignal.csv
%
% Auto-generated by MATLAB on 14-May-2019 21:09:53

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\Serkan\git\cmpe362hw3\exampleSignal.csv", opts);

%% Convert to output type
VarName1 = tbl.VarName1;

%% Clear temporary variables
clear opts tbl



% No filter 
pks = findpeaks(VarName1);
no_filter_peaks_size = size(pks);
disp(no_filter_peaks_size(1));

y1 = lowpass(VarName1,1000,10000);
y2 = lowpass(VarName1,2000,10000);
y3 = lowpass(VarName1,3000,10000);
y4 = lowpass(VarName1,4000,10000);

pks1 = findpeaks(y1);
one_k_filter_peaks_size = size(pks1);
disp(one_k_filter_peaks_size(1));

pks2 = findpeaks(y2);
two_k_filter_peaks_size = size(pks2);
disp(two_k_filter_peaks_size(1));

pks3 = findpeaks(y3);
three_k_filter_peaks_size = size(pks3);
disp(three_k_filter_peaks_size(1));

pks4 = findpeaks(y4);
four_k_filter_peaks_size = size(pks4);
disp(four_k_filter_peaks_size(1));

plot(0:4,[no_filter_peaks_size(1) one_k_filter_peaks_size(1) two_k_filter_peaks_size(1) three_k_filter_peaks_size(1) four_k_filter_peaks_size(1)]);